apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: elastic
spec:
  version: 8.16.1
  count: 1
  elasticsearchRef:
    name: elasticsearch
  image: docker.elastic.co/kibana/kibana:8.16.1
